<a href="https://colab.research.google.com/github/its-Kumar/Machine-Learning/blob/master/Part%208%20-%20Deep%20Learning/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

## Installing Keras

**Now Keras is the part of the tensorflow library So, You don't need to install it seprately**

## Part 1 - Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
tf.__version__

'2.2.0'

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding categorical data


In [5]:
# Encoding the Gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
# Encoding the Geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0)

###  Feature Scaling


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Now let's make the ANN!

### Initialising the ANN



In [10]:
import tensorflow.keras as keras
ann = keras.models.Sequential()

### Adding the input layer and the first hidden layer


In [11]:
ann.add(keras.layers.Dense(units=8,
                                  activation='relu'))

### Adding the second hidden layer


In [12]:
ann.add(keras.layers.Dense(units=8,
                                  activation='relu'))

### Adding the output layer


In [13]:
ann.add(keras.layers.Dense(units=1,
                                  activation='sigmoid'))

### Compiling the ANN


In [14]:
ann.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])

### Fitting the ANN to the Training set


In [15]:
ann.fit(X_train,
               y_train,
               batch_size=25,
               epochs=100)

Epoch 1/100
320/320 [==============================] - 1s 2ms/step - loss: 0.6286 - accuracy: 0.6543
Epoch 2/100
320/320 [==============================] - 1s 2ms/step - loss: 0.4550 - accuracy: 0.8051
Epoch 3/100
320/320 [==============================] - 1s 2ms/step - loss: 0.4303 - accuracy: 0.8133
Epoch 4/100
320/320 [==============================] - 1s 2ms/step - loss: 0.4109 - accuracy: 0.8240
Epoch 5/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3896 - accuracy: 0.8391
Epoch 6/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3720 - accuracy: 0.8457
Epoch 7/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3599 - accuracy: 0.8515
Epoch 8/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3535 - accuracy: 0.8546
Epoch 9/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3502 - accuracy: 0.8549
Epoch 10/100
320/320 [==============================] - 1s 2ms/step - loss: 0.3481 - accura

## Part 3 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [16]:
ann.predict(
    sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
    ) > 0.5

array([[False]])

### Predicting the Test set results


In [17]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate(
    (y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),
    axis =1)
)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1525,   70],
       [ 194,  211]])

In [19]:
accuracy_score(y_test, y_pred)

0.868