# Catboost Regression

## Importing the libraries and dataset

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Data_reg.csv')
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Fitting the Catboost Regression Model to the dataset

In [7]:
from catboost import CatBoostRegressor
regressor = CatBoostRegressor()
regressor.fit(X_train, y_train)

:	learn: 2.9871603	total: 5.09s	remaining: 3.18s
615:	learn: 2.9859904	total: 5.09s	remaining: 3.17s
616:	learn: 2.9851459	total: 5.1s	remaining: 3.17s
617:	learn: 2.9836046	total: 5.11s	remaining: 3.16s
618:	learn: 2.9818941	total: 5.12s	remaining: 3.15s
619:	learn: 2.9807511	total: 5.13s	remaining: 3.14s
620:	learn: 2.9797632	total: 5.14s	remaining: 3.14s
621:	learn: 2.9790341	total: 5.16s	remaining: 3.13s
622:	learn: 2.9779114	total: 5.17s	remaining: 3.13s
623:	learn: 2.9772387	total: 5.18s	remaining: 3.12s
624:	learn: 2.9757154	total: 5.18s	remaining: 3.11s
625:	learn: 2.9746558	total: 5.2s	remaining: 3.1s
626:	learn: 2.9736715	total: 5.2s	remaining: 3.1s
627:	learn: 2.9728992	total: 5.21s	remaining: 3.09s
628:	learn: 2.9718643	total: 5.22s	remaining: 3.08s
629:	learn: 2.9708515	total: 5.22s	remaining: 3.07s
630:	learn: 2.9695639	total: 5.23s	remaining: 3.06s
631:	learn: 2.9683444	total: 5.24s	remaining: 3.05s
632:	learn: 2.9671326	total: 5.25s	remaining: 3.04s
633:	learn: 2.966177

## Predicting a new result

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.31 431.23]
 [457.65 460.01]
 [461.98 461.14]
 ...
 [471.7  473.26]
 [438.86 438.  ]
 [462.71 463.28]]


## Evaluating Model Performance

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9664195873489176