# Polynomial Regression

## Importing the libraries and dataset

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
dataset.head()


AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values


## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)


## Fitting Polynomial Regression to the dataset and Evaluating Model performance

In [5]:
# Fitting Polynomial Regression to the dataset
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_reg = PolynomialFeatures(degree=2)
X_poly = poly_reg.fit_transform(X_train)

regressor = LinearRegression()
regressor.fit(X_poly, y_train)


LinearRegression()

In [6]:
np.set_printoptions(precision=2)
y_pred = regressor.predict(poly_reg.transform(X_test))
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[434.69 431.23]
 [462.68 460.01]
 [472.75 461.14]
 ...
 [470.07 473.26]
 [448.16 438.  ]
 [466.47 463.28]]


In [7]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)


0.8296291565257558

In [8]:
# Fitting Polynomial Regression to the dataset
poly_reg = PolynomialFeatures(degree=3)
X_poly = poly_reg.fit_transform(X_train)

regressor = LinearRegression()
regressor.fit(X_poly, y_train)


LinearRegression()

In [9]:
y_pred = regressor.predict(poly_reg.transform(X_test))
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[436.13 431.23]
 [465.04 460.01]
 [471.86 461.14]
 ...
 [471.23 473.26]
 [445.81 438.  ]
 [465.15 463.28]]


In [10]:
r2_score(y_test, y_pred)


0.8345632751129548

In [11]:
# Fitting Polynomial Regression to the dataset
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train)

regressor = LinearRegression()
regressor.fit(X_poly, y_train)


LinearRegression()

In [12]:
y_pred = regressor.predict(poly_reg.transform(X_test))
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


[[431.06 431.23]
 [463.38 460.01]
 [470.46 461.14]
 ...
 [470.29 473.26]
 [443.2  438.  ]
 [466.89 463.28]]


In [13]:
r2_score(y_test, y_pred)


0.8418720571484963